# Generated by Django 5.2.1 on 2025-05-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_view', 'Can view records'), ('can_edit', 'Can edit records'), ('can_delete', 'Can delete records'), ('can_update', 'Can update records'), ('can_access_data_entry', 'Can access data entry page'), ('can_access_data_edit', 'Can access data edit page'), ('can_access_enquiry', 'Can access enquiry page'), ('can_access_branch_dep_link', 'Can access branch department link page'), ('can_access_bulk_upload', 'Can access bulk upload page'), ('can_access_department', 'Can access department page'), ('can_access_division_branch', 'Can access division branch page'), ('can_access_logo_upload', 'Can access logo upload page'), ('can_access_sub_department', 'Can access sub department page'), ('can_access_create_user', 'Can access create user page'), ('can_access_password_change', 'Can access password change page'), ('can_access_user_list', 'Can access user list page'), ('can_access_user_rights', 'Can access user rights page'), ('can_access_log_report', 'Can access log report page'), ('can_access_register', 'Can access register page')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
