# Generated by Django 5.2.1 on 2025-05-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_can_access_password_change_user_can_access_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_view', 'Can view records'), ('can_edit', 'Can edit records'), ('can_delete', 'Can delete records'), ('can_update', 'Can update records'), ('can_access_data', 'Can access data management'), ('can_access_setup', 'Can access setup'), ('can_access_user', 'Can access user management'), ('can_access_report', 'Can access reports'), ('can_access_data_entry', 'Can access data entry'), ('can_access_data_edit', 'Can access data edit'), ('can_access_enquiry', 'Can access enquiry'), ('can_access_department', 'Can access department'), ('can_access_sub_department', 'Can access sub department'), ('can_access_division_branch', 'Can access division branch'), ('can_access_branch_dep_link', 'Can access branch department link'), ('can_access_logo_upload', 'Can access logo upload'), ('can_access_bulk_upload', 'Can access bulk upload'), ('can_access_users', 'Can access users'), ('can_view_users', 'Can view users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users'), ('can_update_users', 'Can update users'), ('can_access_user_rights', 'Can access user rights'), ('can_view_user_rights', 'Can view user rights'), ('can_edit_user_rights', 'Can edit user rights'), ('can_delete_user_rights', 'Can delete user rights'), ('can_update_user_rights', 'Can update user rights'), ('can_access_password_change', 'Can access password change'), ('can_view_password_change', 'Can view password change'), ('can_edit_password_change', 'Can edit password change'), ('can_delete_password_change', 'Can delete password change'), ('can_update_password_change', 'Can update password change'), ('can_access_log_report', 'Can access log report'), ('can_view_log_report', 'Can view log report'), ('can_edit_log_report', 'Can edit log report'), ('can_delete_log_report', 'Can delete log report'), ('can_update_log_report', 'Can update log report'), ('can_access_register', 'Can access register'), ('can_view_register', 'Can view register'), ('can_edit_register', 'Can edit register'), ('can_delete_register', 'Can delete register'), ('can_update_register', 'Can update register')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
