# Generated by Django 5.2.1 on 2025-05-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_branch_dep_link',
            field=models.BooleanField(default=False, verbose_name='Access Branch Department Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_bulk_upload',
            field=models.BooleanField(default=False, verbose_name='Access Bulk Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_data',
            field=models.BooleanField(default=False, verbose_name='Access Data Management'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_data_edit',
            field=models.BooleanField(default=False, verbose_name='Access Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_data_entry',
            field=models.BooleanField(default=False, verbose_name='Access Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_department',
            field=models.BooleanField(default=False, verbose_name='Access Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_division_branch',
            field=models.BooleanField(default=False, verbose_name='Access Division Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_enquiry',
            field=models.BooleanField(default=False, verbose_name='Access Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_log_report',
            field=models.BooleanField(default=False, verbose_name='Access Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_logo_upload',
            field=models.BooleanField(default=False, verbose_name='Access Logo Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_register',
            field=models.BooleanField(default=False, verbose_name='Access Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_report',
            field=models.BooleanField(default=False, verbose_name='Access Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_setup',
            field=models.BooleanField(default=False, verbose_name='Access Setup'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_sub_department',
            field=models.BooleanField(default=False, verbose_name='Access Sub Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_data_edit',
            field=models.BooleanField(default=False, verbose_name='Delete Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_data_entry',
            field=models.BooleanField(default=False, verbose_name='Delete Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_department',
            field=models.BooleanField(default=False, verbose_name='Delete Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_enquiry',
            field=models.BooleanField(default=False, verbose_name='Delete Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_log_report',
            field=models.BooleanField(default=False, verbose_name='Delete Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_password_change',
            field=models.BooleanField(default=False, verbose_name='Delete Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_register',
            field=models.BooleanField(default=False, verbose_name='Delete Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_user_rights',
            field=models.BooleanField(default=False, verbose_name='Delete User Rights'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_data_edit',
            field=models.BooleanField(default=False, verbose_name='Edit Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_data_entry',
            field=models.BooleanField(default=False, verbose_name='Edit Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_department',
            field=models.BooleanField(default=False, verbose_name='Edit Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_enquiry',
            field=models.BooleanField(default=False, verbose_name='Edit Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_log_report',
            field=models.BooleanField(default=False, verbose_name='Edit Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_password_change',
            field=models.BooleanField(default=False, verbose_name='Edit Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_register',
            field=models.BooleanField(default=False, verbose_name='Edit Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_user_rights',
            field=models.BooleanField(default=False, verbose_name='Edit User Rights'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_data_edit',
            field=models.BooleanField(default=False, verbose_name='Update Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_data_entry',
            field=models.BooleanField(default=False, verbose_name='Update Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_department',
            field=models.BooleanField(default=False, verbose_name='Update Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_enquiry',
            field=models.BooleanField(default=False, verbose_name='Update Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_log_report',
            field=models.BooleanField(default=False, verbose_name='Update Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_password_change',
            field=models.BooleanField(default=False, verbose_name='Update Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_register',
            field=models.BooleanField(default=False, verbose_name='Update Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_user_rights',
            field=models.BooleanField(default=False, verbose_name='Update User Rights'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_data_edit',
            field=models.BooleanField(default=False, verbose_name='View Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_data_entry',
            field=models.BooleanField(default=False, verbose_name='View Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_department',
            field=models.BooleanField(default=False, verbose_name='View Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_enquiry',
            field=models.BooleanField(default=False, verbose_name='View Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_log_report',
            field=models.BooleanField(default=False, verbose_name='View Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_password_change',
            field=models.BooleanField(default=False, verbose_name='View Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_register',
            field=models.BooleanField(default=False, verbose_name='View Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_user_rights',
            field=models.BooleanField(default=False, verbose_name='View User Rights'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_password_change',
            field=models.BooleanField(default=False, verbose_name='Access Password Change'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_users',
            field=models.BooleanField(default=False, verbose_name='Access Users'),
        ),
    ]
