# Generated by Django 5.2.1 on 2025-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_user_can_access_branch_dep_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_access_data', 'Can access data management'), ('can_access_setup', 'Can access setup'), ('can_access_user', 'Can access user management'), ('can_access_report', 'Can access reports'), ('can_access_data_entry', 'Can access data entry'), ('can_access_data_edit', 'Can access data edit'), ('can_access_enquiry', 'Can access enquiry'), ('can_access_department', 'Can access department'), ('can_access_sub_department', 'Can access sub department'), ('can_access_division_branch', 'Can access division branch'), ('can_access_branch_dep_link', 'Can access branch department link'), ('can_access_logo_upload', 'Can access logo upload'), ('can_access_bulk_upload', 'Can access bulk upload'), ('can_access_users', 'Can access users'), ('can_view_users', 'Can view users'), ('can_delete_users', 'Can delete users'), ('can_update_users', 'Can update users'), ('can_access_user_rights', 'Can access user rights'), ('can_view_user_rights', 'Can view user rights'), ('can_delete_user_rights', 'Can delete user rights'), ('can_update_user_rights', 'Can update user rights'), ('can_access_password_change', 'Can access password change'), ('can_view_password_change', 'Can view password change'), ('can_delete_password_change', 'Can delete password change'), ('can_update_password_change', 'Can update password change'), ('can_access_log_report', 'Can access log report'), ('can_view_log_report', 'Can view log report'), ('can_delete_log_report', 'Can delete log report'), ('can_update_log_report', 'Can update log report'), ('can_access_register', 'Can access register'), ('can_view_register', 'Can view register'), ('can_delete_register', 'Can delete register'), ('can_update_register', 'Can update register')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_data_edit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_data_entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_enquiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_log_report',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_password_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_register',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_user_rights',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_edit_users',
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_branch_dep_link',
            field=models.BooleanField(default=False, verbose_name='Delete Branch Department Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_bulk_upload',
            field=models.BooleanField(default=False, verbose_name='Delete Bulk Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_division_branch',
            field=models.BooleanField(default=False, verbose_name='Delete Division Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_logo_upload',
            field=models.BooleanField(default=False, verbose_name='Delete Logo Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_sub_department',
            field=models.BooleanField(default=False, verbose_name='Delete Sub Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_branch_dep_link',
            field=models.BooleanField(default=False, verbose_name='Update Branch Department Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_bulk_upload',
            field=models.BooleanField(default=False, verbose_name='Update Bulk Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_division_branch',
            field=models.BooleanField(default=False, verbose_name='Update Division Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_logo_upload',
            field=models.BooleanField(default=False, verbose_name='Update Logo Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_sub_department',
            field=models.BooleanField(default=False, verbose_name='Update Sub Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_branch_dep_link',
            field=models.BooleanField(default=False, verbose_name='View Branch Department Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_bulk_upload',
            field=models.BooleanField(default=False, verbose_name='View Bulk Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_division_branch',
            field=models.BooleanField(default=False, verbose_name='View Division Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_logo_upload',
            field=models.BooleanField(default=False, verbose_name='View Logo Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_sub_department',
            field=models.BooleanField(default=False, verbose_name='View Sub Department'),
        ),
    ]
