# Generated by Django 5.2.1 on 2025-05-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_custom_permissions'),
        ('dashboard', '0008_alter_user_options_remove_user_can_edit_data_edit_and_more'),
    ]

    operations = [
    ]
