# Generated by Django 5.2.1 on 2025-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_subdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Division/Branch',
                'verbose_name_plural': 'Divisions/Branches',
                'ordering': ['division_id'],
            },
        ),
    ]
