# Generated by Django 5.2.1 on 2025-05-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_divisionbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.divisionbranch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
