# Generated by Django 5.2.1 on 2025-05-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_department_division_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dashboard.divisionbranch'),
            preserve_default=False,
        ),
    ]
