# Generated by Django 5.2.1 on 2025-05-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_department_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(help_text='Unique identifier for the department', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(help_text='Division this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dashboard.divisionbranch'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Name of the department', max_length=100),
        ),
    ]
