# Generated by Django 5.2.1 on 2025-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='division',
        ),
    ]
