# Generated by Django 5.2.1 on 2025-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_department_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_access_data', 'Can access data management'), ('can_access_setup', 'Can access setup'), ('can_access_user', 'Can access user management'), ('can_access_report', 'Can access reports'), ('can_access_data_entry', 'Can access data entry'), ('can_access_data_edit', 'Can access data edit'), ('can_access_enquiry', 'Can access enquiry'), ('can_access_department', 'Can access department'), ('can_access_sub_department', 'Can access sub department'), ('can_access_division_branch', 'Can access division branch'), ('can_access_branch_dep_link', 'Can access branch department link'), ('can_access_logo_upload', 'Can access logo upload'), ('can_access_bulk_upload', 'Can access bulk upload'), ('can_access_users', 'Can access users'), ('can_view_users', 'Can view users'), ('can_create_users', 'Can create users'), ('can_delete_users', 'Can delete users'), ('can_update_users', 'Can update users'), ('can_access_user_rights', 'Can access user rights'), ('can_view_user_rights', 'Can view user rights'), ('can_create_user_rights', 'Can create user rights'), ('can_delete_user_rights', 'Can delete user rights'), ('can_update_user_rights', 'Can update user rights'), ('can_access_password_change', 'Can access password change'), ('can_view_password_change', 'Can view password change'), ('can_create_password_change', 'Can create password change'), ('can_delete_password_change', 'Can delete password change'), ('can_update_password_change', 'Can update password change'), ('can_access_log_report', 'Can access log report'), ('can_view_log_report', 'Can view log report'), ('can_create_log_report', 'Can create log report'), ('can_delete_log_report', 'Can delete log report'), ('can_update_log_report', 'Can update log report'), ('can_access_register', 'Can access register'), ('can_view_register', 'Can view register'), ('can_create_register', 'Can create register'), ('can_delete_register', 'Can delete register'), ('can_update_register', 'Can update register')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_branch_dep_link',
            field=models.BooleanField(default=False, verbose_name='Create Branch Department Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_bulk_upload',
            field=models.BooleanField(default=False, verbose_name='Create Bulk Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_data_edit',
            field=models.BooleanField(default=False, verbose_name='Create Data Edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_data_entry',
            field=models.BooleanField(default=False, verbose_name='Create Data Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_department',
            field=models.BooleanField(default=False, verbose_name='Create Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_division_branch',
            field=models.BooleanField(default=False, verbose_name='Create Division Branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_enquiry',
            field=models.BooleanField(default=False, verbose_name='Create Enquiry'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_log_report',
            field=models.BooleanField(default=False, verbose_name='Create Log Report'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_logo_upload',
            field=models.BooleanField(default=False, verbose_name='Create Logo Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_password_change',
            field=models.BooleanField(default=False, verbose_name='Create Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_register',
            field=models.BooleanField(default=False, verbose_name='Create Register'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_sub_department',
            field=models.BooleanField(default=False, verbose_name='Create Sub Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_user_rights',
            field=models.BooleanField(default=False, verbose_name='Create User Rights'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_users',
            field=models.BooleanField(default=False, verbose_name='Create Users'),
        ),
    ]
