# Generated by Django 5.2.1 on 2025-05-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDepartmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='dashboard.divisionbranch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='dashboard.department')),
                ('sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='dashboard.subdepartment')),
            ],
            options={
                'verbose_name': 'Branch Department Link',
                'verbose_name_plural': 'Branch Department Links',
                'ordering': ['branch', 'department', 'sub_department'],
                'unique_together': {('branch', 'department', 'sub_department')},
            },
        ),
    ]
