# Generated by Django 5.2.1 on 2025-05-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='dashboard.subdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sub-Department Assignment',
                'verbose_name_plural': 'User Sub-Department Assignments',
                'unique_together': {('user', 'sub_department')},
            },
        ),
    ]
