# Generated by Django 5.2.1 on 2025-05-21 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_usersubdepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubdepartment',
            options={'verbose_name': 'User SubDepartment Mapping', 'verbose_name_plural': 'User SubDepartment Mappings'},
        ),
        migrations.AlterUniqueTogether(
            name='usersubdepartment',
            unique_together={('user',)},
        ),
        migrations.AddField(
            model_name='usersubdepartment',
            name='mappings',
            field=models.JSONField(default=dict, help_text='JSON containing subdepartment mappings with their branch and department IDs'),
        ),
        migrations.AlterField(
            model_name='usersubdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usersubdepartment',
            name='sub_department',
        ),
    ]
