# Generated by Django 5.2.1 on 2025-05-21 10:57

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_usersubdepartment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_values', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.divisionbranch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Entry Record',
                'verbose_name_plural': 'Data Entry Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataEntryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_data', models.BinaryField()),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.dataentryrecord')),
            ],
            options={
                'verbose_name': 'Data Entry File',
                'verbose_name_plural': 'Data Entry Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
