# Generated by Django 5.2.1 on 2025-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_dataentryrecord_dataentryfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='organization_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
